services:
  php82:
    container_name: sieve-package-php82
    build:
      context: .
      dockerfile: .docker/php82/Dockerfile
      args:
        - SSH_PRIVATE_KEY
    volumes:
      - './:/app'
    networks:
      - sieve-package
    extra_hosts:
      - "host..xdebug.internal:host-gateway"
  php83:
    container_name: sieve-package-php83
    build:
      context: .
      dockerfile: .docker/php83/Dockerfile
      args:
        - SSH_PRIVATE_KEY
    volumes:
      - './:/app'
    networks:
      - sieve-package
    extra_hosts:
      - "host..xdebug.internal:host-gateway"

networks:
  sieve-package:
    name: ${SIEVE_PACKAGE_NETWORK:-sieve-package}

