name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
      - cron: '0 0 * * *'

jobs:
    php-tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: [8.1, 8.0]

        name: PHP${{ matrix.php }} - ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Install dependencies
              run: |
                  sudo composer self-update
                  composer update --prefer-stable --prefer-dist --no-interaction --no-suggest

            - name: Execute tests
              run: vendor/bin/phpunit
              
